language: android
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - build-tools-27.0.3
    - android-28


script:
  - ./gradlew build dependencyUpdates

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
